# Generated by Django 2.0 on 2018-01-09 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('ada_relation', models.CharField(max_length=20)),
                ('pronouns', models.CharField(max_length=50)),
                ('github_username', models.CharField(max_length=50)),
                ('internship_placement', models.CharField(blank=True, max_length=200)),
                ('linkedinURL', models.CharField(blank=True, max_length=200)),
                ('capstone_info', models.TextField(blank=True, max_length=500)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('cohort_served', models.ManyToManyField(to='adaTree.Cohort')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
