# Generated by Django 2.0.1 on 2018-01-17 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_name', models.CharField(max_length=200)),
                ('grad_year', models.CharField(max_length=4)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OptInProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('ada_relation', models.CharField(max_length=100)),
                ('pronouns', models.CharField(max_length=100)),
                ('cohort_served', models.CharField(max_length=100)),
                ('github_username', models.CharField(max_length=100)),
                ('internship_placement', models.TextField(blank=True, max_length=500)),
                ('linkedin', models.CharField(blank=True, max_length=200)),
                ('capstone_info', models.TextField(blank=True, max_length=500)),
                ('email', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('ada_relation', models.CharField(max_length=100)),
                ('pronouns', models.CharField(max_length=100)),
                ('cohort_served', models.CharField(max_length=100)),
                ('github_username', models.CharField(max_length=100)),
                ('internship_placement', models.TextField(blank=True, max_length=500)),
                ('linkedin', models.CharField(blank=True, max_length=200)),
                ('capstone_info', models.TextField(blank=True, max_length=500)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
