# Generated by Django 2.0 on 2018-01-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adaTree', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='linkedinURL',
            new_name='linkedin',
        ),
    ]
