# Generated by Django 2.0 on 2018-01-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaTree', '0002_auto_20180109_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptInProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('ada_relation', models.CharField(max_length=100)),
                ('pronouns', models.CharField(max_length=100)),
                ('cohort_served', models.CharField(max_length=100)),
                ('github_username', models.CharField(max_length=100)),
                ('internship_placement', models.TextField(blank=True, max_length=500)),
                ('linkedin', models.CharField(blank=True, max_length=200)),
                ('capstone_info', models.TextField(blank=True, max_length=500)),
                ('email', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
