# Generated by Django 2.0.1 on 2018-01-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaTree', '0005_auto_20180116_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='grad_year',
            field=models.TextField(default=9999, max_length=4),
            preserve_default=False,
        ),
    ]
