# Generated by Django 2.0.1 on 2018-01-22 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adaTree', '0007_auto_20180119_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='optinprofile',
            name='internship_company',
            field=models.ForeignKey(blank=True, default=99999999, on_delete=django.db.models.deletion.CASCADE, to='adaTree.InternshipCompany'),
            preserve_default=False,
        ),
    ]
