# Generated by Django 2.0.1 on 2018-01-22 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adaTree', '0008_optinprofile_internship_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='optinprofile',
            name='internship_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adaTree.InternshipCompany'),
        ),
    ]
