# Generated by Django 2.0.1 on 2018-01-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaTree', '0010_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='optinprofile',
            name='capstone_tech',
            field=models.ManyToManyField(to='adaTree.CapstoneTech'),
        ),
    ]
